name: Fetch Epgshare01 Data

on:
  schedule:
    - cron: "0 0 */3 * *" # Runs every 3 days at midnight UTC
  workflow_dispatch:

jobs:
  process-xml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: pip install requests

      - name: Run Script
        run: |
          mkdir -p data
          python epgshare01Fetch.py

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Force Update File
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add data/tvg-ids.json
          git commit -m "Update tvg-ids.json"
          git push --force
